kind: pipeline
type: digitalocean
name: default

token:
  from_secret: GIT_TOKEN
platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: build -release
    settings:
     environment:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - GRADLE_USER_HOME=.gradleHome
     commands:
      - ./gradlew release
      - sh uploadapk.sh
---
kind: pipeline
name: publish github pages

steps:
  - name: publish
    image: plugins/github-release
    pages_directory: https://github.com/Lediya/SampleTest/
    settings:
      username:
        from_secret: GIT_USERNAME
      api_key:
        from_secret: GIT_TOKEN
      pubilc_url:
        from_secret: https://api.github.com/Lediya/SampleTest/app/
      build: 1.0
      files: dist/*
      tags:
        - "latest"
      environment:
        - GRADLE_OPTS=-Dorg.gradle.daemon=false
        - GRADLE_USER_HOME=.gradleHome
      commands:
        - ./gradlew release
        - curl -u username:api_key -X PUT  pubilc_url/build.apk --upload-file build/outputs/apk/qa/debug/qa-debug-*.apk
      when:
        event: tag
        status: success
        ref: refs/tags/master*

