kind: pipeline
name: generic

platform:
  arch: arm64
  os: linux

steps:
- name: build
  image: golang:1.13
  depdendencies:
    environment:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - GRADLE_USER_HOME=.gradleHome
    commands:
      - ./gradlew assembleQaDebug
      - sh scripts/uploadArtifact.sh
---
kind: pipeline
name: publish github pages

steps:
  - name: publish
    image: plugins/github-release
    pages_directory: https://github.com/Lediya/SampleTest/
    settings:
      username:
        from_secret: GIT_USERNAME
      api_key:
        from_secret: GIT_TOKEN
      pubilc_url:
        from_secret: https://api.github.com/Lediya/SampleTest/app/
      build: 1.0
      files: dist/*
      tags:
        - "latest"
      files: dist/*
      checksum:
       - sha256
      environment:
        - GRADLE_OPTS=-Dorg.gradle.daemon=false
        - GRADLE_USER_HOME=.gradleHome
      commands:
        - ./gradlew release
        -if ! test -e build/outputs/apk/qa/debug/qa-debug-*.apk ; then
         exit 1
          fi
         echo "Uploaded artifact to $BUILD.apk"
        - curl -u username:api_key -X PUT  pubilc_url/build.apk --upload-file build/outputs/apk/qa/debug/qa-debug-*.apk
      when:
        event: tag
        status: success
        ref: refs/tags/master*

